### ISSUE TITLE
Creating frames from NMR structure from CSV returns error

### ISSUE THREAD

**Issue by universvm** [wells-wood-research/aposteriori#36]
I got the following error:
```
/home/s1622572/anaconda3/envs/timed/lib/python3.7/site-packages/aposteriori/data_prep/create_frame_data_set.py:1099: UserWarning: Selecting the first state from the NMR structure 6b4e
  f"Selecting the first state from the NMR structure {pdb_structure.id}"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/s1622572/anaconda3/envs/timed/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/s1622572/anaconda3/envs/timed/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/s1622572/anaconda3/envs/timed/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/s1622572/anaconda3/envs/timed/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/s1622572/anaconda3/envs/timed/lib/python3.7/site-packages/aposteriori/data_prep/cli.py", line 204, in cli
    pathlib.Path(download_file)
  File "/home/s1622572/anaconda3/envs/timed/lib/python3.7/site-packages/aposteriori/data_prep/create_frame_data_set.py", line 1206, in download_pdb_from_csv_file
    for pdb_code in pdb_list
  File "/home/s1622572/anaconda3/envs/timed/lib/python3.7/site-packages/aposteriori/data_prep/create_frame_data_set.py", line 1206, in <listcomp>
    for pdb_code in pdb_list
  File "/home/s1622572/anaconda3/envs/timed/lib/python3.7/site-packages/aposteriori/data_prep/create_frame_data_set.py", line 1168, in _fetch_pdb
    _ = _select_pdb_chain(output_path, chain)
  File "/home/s1622572/anaconda3/envs/timed/lib/python3.7/site-packages/aposteriori/data_prep/create_frame_data_set.py", line 1103, in _select_pdb_chain
    chain_pdb = pdb_structure[chain]
  File "/home/s1622572/anaconda3/envs/timed/lib/python3.7/site-packages/ampal/assembly.py", line 176, in __getitem__
    return id_dict[item]
KeyError: 'A'
```

I suspect it has something to do with the selection of the states from the NMR structure and possibly the type returned is not a dictionary. 

We could try first selecting the chain and then the state.

**Comment by universvm** [comment]
Turns out it was just a malformed PDB with a weird chain.
